version: '2'
services:
    musicbible-app:
        image: musicbible
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://musicbible-mysql:3306/musicbible?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    musicbible-mysql:
        extends:
            file: mysql.yml
            service: musicbible-mysql
